services:
  quiz-service:
    build: 
      context: ./backend/quiz-service
      args:
        APP_BANNER: "Quiz Service DEV"
    command: npm run dev
    volumes:
      - ./backend/quiz-service:/app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - AUTH_SERVICE_URL=http://auth-service:5003
      - APP_BANNER=Quiz Service DEV
    depends_on:
      - mongo
    networks:
      - quiznet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    secrets:
      - jwt_secret
  
  auth-service:
    build: 
      context: ./backend/auth-service
      args:
        APP_BANNER: "Auth Service DEV"
    command: npm run dev
    volumes:
      - ./backend/auth-service:/app
    ports:
      - "5003:5003"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - APP_BANNER=Auth Service DEV
    depends_on:
      - mongo
    networks:
      - quiznet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/"]
      interval: 30s
      timeout: 10s
      retries: 3
    secrets:
      - jwt_secret

  user-service:
    build: 
      context: ./backend/user-service
      args:
        APP_BANNER: "User Service DEV"
    command: npm run dev
    volumes:
      - ./backend/user-service:/app
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - AUTH_SERVICE_URL=http://auth-service:5003
      - APP_BANNER=User Service DEV
    depends_on:
      - mongo
    networks:
      - quiznet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/"]
      interval: 30s
      timeout: 10s
      retries: 3
    secrets:
      - jwt_secret

  stats-service:
    build: 
      context: ./backend/stats-service
      args:
        APP_BANNER: "Stats Service DEV"
    command: npm run dev
    volumes:
      - ./backend/stats-service:/app
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - AUTH_SERVICE_URL=http://auth-service:5003
      - APP_BANNER=Stats Service DEV
    depends_on:
      - mongo
    networks:
      - quiznet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    secrets:
      - jwt_secret

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - quiznet
    environment:
      - CHOKIDAR_USEPOLLING=true

  proxy:
    build:
      context: ./backend/proxy
      args: 
        APP_BANNER: "Proxy Service DEV"
    command: npm run dev
    volumes:
      - ./backend/proxy:/app
    ports:
      - "3001:3001"
    environment:
      - APP_BANNER=Proxy Service DEV
    networks:
      - quiznet
    depends_on:
      - quiz-service
      - auth-service
      - user-service
      - stats-service

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - quiznet
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  

networks:
  quiznet:


volumes:
  mongo_data:
