FROM node:18-alpine

WORKDIR /app

ARG APP_BANNER="Quiz App"
ARG APP_PORT=5000

ENV APP_BANNER=$APP_BANNER

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE ${APP_PORT}

RUN which curl

CMD echo "$APP_BANNER" && npm run dev